### ISSUE TITLE
hint of next step na een foute invoer in equivalentiebewijzen

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#125]
bij het omschrijven naar normaalvormen kun je een hint of volgende stap krijgen als je een fout hebt gemaakt. Bij de equivalentiebewijzen gaat dit niet goed:
![image](https://user-images.githubusercontent.com/16118925/119113167-1beceb80-ba25-11eb-8be0-f2aeed4ad7d2.png)

**Comment by BenEdV** [comment]
Er was een verandering in de backend waardoor we de communicatie met de backend moest aanpassen. Deze is inmiddels al verholpen op de nieuwste versie.
