### ISSUE TITLE
aangeven welke regel moet worden toegepast blijft staan ook als ik vervolgens wel een regel kies

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#170]
aangeven welke regel moet worden toegepast blijft staan ook als ik vervolgens wel een regel kies
![image](https://user-images.githubusercontent.com/16118925/121534129-394c1e80-ca01-11eb-8422-dfe11093b56d.png)

**Comment by BenEdV** [comment]
Ik zie dat de backend voor deze nu de buggyRule regel `logic.propositional.buggy.demorgan4` geeft terwijl we in de taalbestaanden alleen `logic.propositional.buggy.demorgan4.inv` hebben. Moet ik de `.inv` weghalen of zijn dit 2 verschillende regels? Er zijn 8 andere regels met een `.inv` ik weet niet of er ook hetzelfde aan de hand is.

**Comment by BenEdV** [comment]
Ja ik heb verder gekeken en inderdaad het zijn allemaal verschillende regels en we missen de teksten voor de niet `.inv` versies. Dit is iets lastiger dan normaal want de taalbestanden ondersteunen op dit moment niet dat je een key kan hebben met een punt na de naam van een andere key (bijv. `logic.propositional.buggy.demorgan4` en `logic.propositional.buggy.demorgan4.inv`). Ik zal een speciaal teken toevoegen voor de 'root' key van een dictionary.

**Comment by josjelodder** [comment]
Ok, dank je, Josje

Van: Ben de Vries ***@***.***>
Verzonden: donderdag 10 juni 2021 15:59
Aan: ideas-edu/logictools ***@***.***>
CC: Lodder, Josje ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ideas-edu/logictools] aangeven welke regel moet worden toegepast blijft staan ook als ik vervolgens wel een regel kies (#170)


Ja ik heb verder gekeken en inderdaad het zijn allemaal verschillende regels en we missen de teksten voor de niet .inv versies. Dit is iets lastiger dan normaal want de taalbestanden ondersteunen op dit moment niet dat je een key kan hebben met een punt na de naam van een andere key (bijv. logic.propositional.buggy.demorgan4 en logic.propositional.buggy.demorgan4.inv). Ik zal een speciaal teken toevoegen voor de 'root' key van een dictionary.
