### ISSUE TITLE
close regel deductiestelling 1

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#197]
de vertaling ontbreekt hier nog,ipv daarvan de lange reeks ...
![image](https://user-images.githubusercontent.com/16118925/123105963-846e2480-d438-11eb-8b59-30d81ba40ef0.png)

**Comment by BenEdV** [comment]
Dit is vergelijkbaar met het probleem dat we met `Modus Ponens` v `modusponens` hadden in de backend. @BastiaanHeeren Is deze makkelijk te vervangen in de backend zodat er `deduction.close` in de communicatie staat i.p.v. `logic.propositional.axiomatic.deduction.close`? Anders kan ik hem in de frontend hardcoden.

**Comment by BenEdV** [comment]
Dit is nu opgelost op de backend
