### ISSUE TITLE
punt voor hulpstelling weg

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#213]
Voor de hulpstelling in de beschrijving van de opgave staat een soort lijst bullet, kan die weg?

**Comment by BenEdV** [comment]
Wil je dat het allemaal op dezelfde regel is?

**Comment by josjelodder** [comment]
Ik denk dat het mooiste of dezelfde regel, of links uitlijnen zodat het na de “Opgave”  in de regel erboven komt te staan

Van: Ben de Vries ***@***.***>
Verzonden: vrijdag 25 juni 2021 12:35
Aan: ideas-edu/logictools ***@***.***>
CC: Lodder, Josje ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ideas-edu/logictools] punt voor hulpstelling weg (#213)


Wil je dat het allemaal op dezelfde regel is?
