### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#287]
Als ik na een geval phi ./\ psi ook een geval psi /\ phi aanmaak, verstuurd hij niets naar de backend, en lijkt er een fout op te treden
![image](https://user-images.githubusercontent.com/16118925/144580840-d1996baf-b8b5-4d3a-890b-77c2a0ef7738.png)

**Comment by BenEdV** [comment]
Als een geval al voltooid is kan de gebruiker expliciet het geval verwijderen. Echter de gebruiker opnieuw de geval probeert te bewijzen geeft de tool een foutmelding.
