### ISSUE TITLE
meesturen prefix

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#303]
Onze output stuurt een prefix mee (die bijhoudt waar we in de strategie zitten, die zou jij bij de input weer mee terug moeten sturen. Ik ontdekte het in logax maar zie dat het ook in logex gebeurt:

Input
{"service":"onefirst","state":{"exerciseid":"logic.propositional.dnf.unicode","prefix":"[]","context":{"term":"¬(q → r) ∨ q ∨ r","environment":{},"location":[]},"userid":"5","session":"a399ffa787678c319527","taskid":"¬(q → r) ∨ q ∨ r"},"source":"logex"}
Output
{"onefirst":{"first":{"step":{"rule":"logic.propositional.defimpl","location":[0,0],"environment":{}},"state":{"exerciseid":"logic.propositional.dnf.unicode","prefix":"**[0,2,0,0,3,1,0]**","context":{"term":"¬(¬q ∨ r) ∨ q ∨ r","environment":{},"location":[0,0]},"userid":"5","sessionid":null,"taskid":"¬(q → r) ∨ q ∨ r"}}},"version":"1.8.1 (27a352d26571dad5913f9786c09ce5cda3021793)"}

de prefix [0,2,0,0,3,1,0] zou bij een volgende onefirst in de input meemoeten, dat gebeurt nu niet. Idem voor logax:

{"service":"onefirst","state":{"exerciseid":"logic.propositional.logax","prefix":"[]","context":{"term":{"proof":[{"number":1000,"term":"p, p -> q |- q"}],"lemmas":[]},"environment":{},"location":[]},"userid":"1062886590695368","session":"5375213ea08c308bbdef","taskid":"\n1000. p, p -> q |- q\n"},"source":"test.logax"}
Output
{"onefirst":{"first":{"step":{"rule":"assumption","location":[],"environment":{"subgoals":""}},"state":{"exerciseid":"logic.propositional.logax","prefix":"**[0,0,TList [TCon proof [TCon proofline [TNum 1000,TCon logic.propositional.axiomatic.statement [TList [TVar \"p\",TCon logic1.implies [TVar \"p\",TVar \"q\"]],TVar \"q\"],TCon nothing []]],TList []],0]"**,"context":{"term":{"proof":[{"number":1,"term":"p |- p","label":"assumption"},{"number":1000,"term":"p, p -> q |- q"}],"lemmas":[]},"environment":{},"location":[]},"userid":"1062886590695368","sessionid":null,"taskid":"\n1000. p, p -> q |- q\n"}}},"version":"1.8.1 (27a352d26571dad5913f9786c09ce5cda3021793)"}

**Comment by BenEdV** [comment]
Ik heb oneway en logax aangepast maar ik weet niet zeker hoe logische equivalentie moet worden toegepast. Bij dnv en cnv houd je bij per stap wat de prefix is en als je een aantal stappen verwijdert (wat volledig in de frontend gebeurt) onthoudt je dus wat de oude prefixes zijn. Met leq kan je boven- en onderstappen verwijderen met gevolg dat je een andere "state" kan maken zonder communicatie met de backend. Ik weet ook niet of de prefix afhankelijk is van de huidige richting van het bewijs. Zou de oplossing een "removeStep" commando voor leq zoals bij logax zijn?
