### ISSUE TITLE
invoer formules mogelijk via invoerbordje of toetsenbord pc

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#353]
formules zou je in moeten kunnen voeren door enkel gebruik te maken van toetsenbordje en/of toetsenbord pc: sneltoetsen voor logische tekens en griekse symbolen, + en haakjes op invoertoetsenbordje  Overzicht van sneltoetsen ontbreekt  nog. / heeft een dubbele functie

**Comment by josjelodder** [comment]
ook nog maar hierbij: symbool voor lege verzameling toevoegen

**Comment by BenEdV** [comment]
Welke toets zou je aanraden voor de '∪' en '∅' tekens? Hoe moeten we de lege verzameling naar de backend sturen? Nu stuur ik de ascii teken `∅`. Bedoel je dat '+', '(', ')', '{', en '}' ook in de toetsenbord moet staan? Dan lijkt me dat '-' en '/' ook er bij moeten
