### ISSUE TITLE
kruisjes links werken niet altijd

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#379]
![image](https://user-images.githubusercontent.com/16118925/161978158-16aab1bd-5c5d-4a3a-93f4-428fc2186a58.png)

**Comment by BenEdV** [comment]
Deze is iets complexer. Op het moment weet de voorkant niet of het mogelijk is om een geval te verwijderen. Hiervoor gebruikt de voorkant de `diagnose` call om te kijken of de gewenst staat geldig is.

Bijvoorbeeld als we in het bovenstaande plaatje op het kruisje van Hypothese phi zou drukken stuurt de voorkant de huidige staat met een context zonder de hypothese phi. De achterkant interpreteert alleen dat het geval "en" ongeldig is omdat de hypothese phi ontbreekt en stuurt een foutmelding met `"check-used-metavars: 1 linenr .0:phi not in induction hypothesis"`. 
Als geval "en" het actieve geval is dan laten we een (verwarrende) foutmelding zien met "The metavariable ψ does not occur in the induction hypothesis; formulate this first for ψ or choose another metavariable." en als er geen actieve geval is laten we helemaal geen foutmelding zien.

Er zijn een paar manieren om dit op te lossen
1. We schrijven alle regels van wat wel en niet verwijdert mag worden in de voorkant zelf, dan tonen we de verwijder knop alleen als het mogelijk is om dat geval te verwijderen.
2. De 'diagnose' call op de achterkant herkent wel dat het om een verwijder stap gaat en aan de hand van constraints een helder foutmelding geeft.
3. Als de diagnose call aangeeft dat verwijderen niet mogelijk wordt een generieke "Dit geval kan niet verwijdert worden" foutmelding aan de gebruiker vertoond.
