### ISSUE TITLE
ontbrekende constraint

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#380]
Deze constraint zat nog niet in je lijst:
invalid inductivestep for **OR**  
vertaling: Het connectief …  zit niet in de taal./ The connective ... is not in the language.

**Comment by BenEdV** [comment]
De constraint `check-instance.4:connective not in language: OR"` bestaat ook en deze zit in de tool. Willen we de `invalid inductivestep for OR` constraint ook toevoegen met precies dezelfde tekst?

**Comment by josjelodder** [comment]
ik heb nu hier ook connective not in language van gemaakt

**Comment by josjelodder** [comment]
maar ik zie dat dit niet helpt, er gebeurt aan de voorkant niets als je wilt controleren, terwijl de achterkant wel  connective not in language: OR" teruggeeft
