### ISSUE TITLE
niet werkende constraint

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#383]
de constraint check-instance.0:wrongIHBottom staat wel in het taallijstje (wel later toegevoegd) maar werkt nog niet

**Comment by BenEdV** [comment]
Ik heb geschreven dat hij checkt of `incorrect IHdefinition: invalid instantiation for bottom expr in hypothesis` in de foutmelding van de achterkant meekrijgt. Is dit nog steeds mogelijk of moet ik alleen controleren op de `check-instance.0:wrongIHBottom` foutmelding.?

Dezelfde vraag voor de `wrongIHTop` foutmelding

**Comment by josjelodder** [comment]
nee, je krijgt nu enkel nog de wrongIHTop of wrongIHBottom, ofwel vanuit check-instance, ofwel vanuit check-inductive: 
check-inductive: wrongIHTop
