### ISSUE TITLE
error message wrong relation in logind nog niet vertaald

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#391]
De foutboodschap wrong relation wordt nog niet altijd herkend:
"diagnose":{"diagnosetype":"notequiv","message":"check-inductive: check-triple.BaseStep \"p\" linenr:0:wrong relation"}
![image](https://user-images.githubusercontent.com/16118925/165704102-fd0ba4d1-5218-4a13-8969-7f8c21c2570b.png)

**Comment by BenEdV** [comment]
Deze zou nu moeten opgelost zijn op main
