### ISSUE TITLE
meegeven prefix bij logax

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#407]
als je via toon stap een bewijs doorloopt, geeft de voorkant de prefix niet mee, waardoor niet de meest handige volgorde wordt gekozen

**Comment by BenEdV** [comment]
Hier staat wel dat de prefix meegegeven wordt bij LogAx.
<img width="1800" alt="Screen Shot 2022-07-19 at 22 58 04" src="https://user-images.githubusercontent.com/10991906/179847227-3258c785-e068-42bb-81ad-dba3081f652d.png">

Een ding die wel tegenkom is dat de prefix niet wordt aangepast bij een "undo"/"redo" van een stap. Is dit iets die we willen bijhouden of moeten we zoals bij de anderen de prefix op "[]" zetten als een undo wordt gedaan?

**Comment by josjelodder** [comment]
Dat gaat inderdaad nu wel goed, misschien zwierf er nog een oude versie in mijn cache, want de vorige keer dat ik het probeerde niet, groetjes Josje

Van: Ben de Vries ***@***.***>
Verzonden: dinsdag 19 juli 2022 23:00
Aan: ideas-edu/logictools ***@***.***>
CC: Lodder, Josje ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ideas-edu/logictools] meegeven prefix bij logax (Issue #407)


Hier staat wel dat de prefix meegegeven wordt bij LogAx.
[Screen Shot 2022-07-19 at 22 58 04]<https://user-images.githubusercontent.com/10991906/179847227-3258c785-e068-42bb-81ad-dba3081f652d.png>

Een ding die wel tegenkom is dat de prefix niet wordt aangepast bij een "undo"/"redo" van een stap. Is dit iets die we willen bijhouden of moeten we zoals bij de anderen de prefix op "[]" zetten als een undo wordt gedaan?
