### ISSUE TITLE
kleuring in volgende hint

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#46]
De manier waarop de volgende hint wordt gekleurd zou de subformulestructuur moeten volgen

**Comment by BenEdV** [comment]
Willen we deze anders kleuren?
<img width="1201" alt="Screen Shot 2021-04-13 at 4 33 42 PM" src="https://user-images.githubusercontent.com/10991906/114570577-38537680-9c76-11eb-988e-339957ebc4da.png">
