### ISSUE TITLE
geen hint na validatiefout

### ISSUE THREAD

**Issue by josjelodder** [ideas-edu/logictools#71]
na validatiefout kan ik geen hint meer krijgen:
![image](https://user-images.githubusercontent.com/16118925/114419510-c581c700-9bb3-11eb-8ea5-f7dad477b813.png)

**Comment by BenEdV** [comment]
Ik zie dat je nog op de oude branch aan het testen bent. Kan je dit uittesten op https://www.bendevries.com/logictools/32_syntax/ ?

**Comment by josjelodder** [comment]
Hier lijkt dit inderdaad goed te gaan, maar in deze versie werkt de sneltoets enter niet, groetjes Josje

Van: Ben de Vries ***@***.***>
Verzonden: maandag 12 april 2021 17:46
Aan: ideas-edu/logictools ***@***.***>
CC: Lodder, Josje ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ideas-edu/logictools] geen hint na validatiefout (#71)


Ik zie dat je nog op de oude branch aan het testen bent. Kan je dit uittesten op https://www.bendevries.com/logictools/32_syntax/ ?
